site_name: My Yaml Scheduler
site_description: Documentation for My Yaml Scheduler
site_author: jparisu
repo_url: https://github.com/jparisu/yasched
repo_name: yasched
edit_uri: edit/main/docs/

theme:
  name: readthedocs

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
          options:
            docstring_style: google
            show_source: true
  - include-markdown

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Data Model: data-model.md
  - Agenda Format: agenda-format.md
  - Architecture: architecture.md
  - API: api/index.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jparisu/yasched
