site_name: yasched Documentation
site_description: Scheduler for agenda and tasks orchestration via YAML
site_author: jparisu
site_url: https://jparisu.github.io/yasched

repo_name: jparisu/yasched
repo_url: https://github.com/jparisu/yasched

theme:
  name: readthedocs

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
          - src
          options:
            docstring_style: google
            show_source: true
  - awesome-pages

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - toc:
      permalink: true
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jparisu/yasched
