#!/usr/bin/env bash
# =============================================================================
# Download the web fonts yasched uses and vendor them into the repo.
#
# yasched is local-first: the running app must never make outbound network
# calls. This script is the ONE step that needs the internet, and it is run by
# a maintainer, not by users. It:
#
#   1. asks Google Fonts for the CSS (with a modern browser User-Agent, so the
#      response uses woff2),
#   2. downloads every font file that CSS references into public/fonts/,
#   3. rewrites the CSS to point at those local files and writes src/fonts.css.
#
# The downloaded .woff2 files and the generated src/fonts.css are COMMITTED, so
# a fresh clone builds and runs fully offline. Re-run only to add a family or
# weight (edit FAMILIES below first).
#
#   cd apps/web && ./scripts/fetch-fonts.sh
# =============================================================================
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

FONT_DIR="public/fonts"
CSS_OUT="src/fonts.css"

# Families and weights, exactly as the app uses them (see index.css --app-font
# and --app-font-display). Keep this list in sync with tailwind.config.js.
FAMILIES="family=Nunito:wght@400;500;600;700\
&family=Nunito+Sans:wght@400;500;600\
&family=Inter:wght@400;500;600;700\
&family=JetBrains+Mono:wght@400;500;600;700\
&family=Fredoka:wght@400;500;600;700"

# A modern UA is what makes Google serve woff2 instead of legacy formats.
UA="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36"
CSS_URL="https://fonts.googleapis.com/css2?${FAMILIES}&display=swap"

command -v curl >/dev/null || { echo "ERROR: curl is required." >&2; exit 1; }

echo "▶ fetching font CSS from Google Fonts ..."
raw_css="$(curl -fsSL -H "User-Agent: $UA" "$CSS_URL")" || {
  echo "ERROR: could not reach fonts.googleapis.com (this script needs network)." >&2
  exit 1
}

mkdir -p "$FONT_DIR"

# Collect the remote font URLs, download each once, and remember the mapping so
# the CSS can be rewritten to the local path.
urls="$(grep -oE 'https://fonts\.gstatic\.com/[^)]+\.woff2' <<<"$raw_css" | sort -u)"
[ -n "$urls" ] || { echo "ERROR: no woff2 URLs found in the CSS response." >&2; exit 1; }

count=0
local_css="$raw_css"
while IFS= read -r url; do
  # Name files after the family + a hash-free suffix from the upstream path, so
  # re-running is idempotent and diffs stay readable.
  name="$(sed -E 's#.*/s/([^/]+)/.*#\1#' <<<"$url")-$(basename "$url")"
  dest="$FONT_DIR/$name"
  if [ ! -f "$dest" ]; then
    curl -fsSL -o "$dest" "$url"
    count=$((count + 1))
  fi
  local_css="${local_css//$url//fonts/$name}"
done <<<"$urls"

total="$(wc -l <<<"$urls" | tr -d ' ')"
echo "  downloaded $count new file(s); $total referenced in total."

{
  echo "/* ==========================================================================="
  echo "   GENERATED by scripts/fetch-fonts.sh — do not edit by hand."
  echo ""
  echo "   Self-hosted @font-face rules. Every url() points at public/fonts/, so the"
  echo "   app makes NO outbound network calls at runtime. Re-generate with:"
  echo "       cd apps/web && ./scripts/fetch-fonts.sh"
  echo "   =========================================================================== */"
  echo ""
  printf '%s\n' "$local_css"
} >"$CSS_OUT"

echo "✔ wrote $CSS_OUT and $FONT_DIR/*.woff2 — commit both."
echo "  Verify no CDN references remain:  grep -r fonts.gstatic src/ index.html"
