name: Codespell Spell Checking

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install codespell
        run: |
          python -m pip install --upgrade pip
          pip install codespell
      
      - name: Run codespell
        run: codespell
